require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AutoBrandsController do

  # This should return the minimal set of attributes required to create a valid
  # AutoBrand. As you add validations to AutoBrand, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AutoBrandsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all auto_brands as @auto_brands" do
      auto_brand = AutoBrand.create! valid_attributes
      get :index, {}, valid_session
      assigns(:auto_brands).should eq([auto_brand])
    end
  end

  describe "GET show" do
    it "assigns the requested auto_brand as @auto_brand" do
      auto_brand = AutoBrand.create! valid_attributes
      get :show, {:id => auto_brand.to_param}, valid_session
      assigns(:auto_brand).should eq(auto_brand)
    end
  end

  describe "GET new" do
    it "assigns a new auto_brand as @auto_brand" do
      get :new, {}, valid_session
      assigns(:auto_brand).should be_a_new(AutoBrand)
    end
  end

  describe "GET edit" do
    it "assigns the requested auto_brand as @auto_brand" do
      auto_brand = AutoBrand.create! valid_attributes
      get :edit, {:id => auto_brand.to_param}, valid_session
      assigns(:auto_brand).should eq(auto_brand)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AutoBrand" do
        expect {
          post :create, {:auto_brand => valid_attributes}, valid_session
        }.to change(AutoBrand, :count).by(1)
      end

      it "assigns a newly created auto_brand as @auto_brand" do
        post :create, {:auto_brand => valid_attributes}, valid_session
        assigns(:auto_brand).should be_a(AutoBrand)
        assigns(:auto_brand).should be_persisted
      end

      it "redirects to the created auto_brand" do
        post :create, {:auto_brand => valid_attributes}, valid_session
        response.should redirect_to(AutoBrand.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved auto_brand as @auto_brand" do
        # Trigger the behavior that occurs when invalid params are submitted
        AutoBrand.any_instance.stub(:save).and_return(false)
        post :create, {:auto_brand => { "name" => "invalid value" }}, valid_session
        assigns(:auto_brand).should be_a_new(AutoBrand)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AutoBrand.any_instance.stub(:save).and_return(false)
        post :create, {:auto_brand => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested auto_brand" do
        auto_brand = AutoBrand.create! valid_attributes
        # Assuming there are no other auto_brands in the database, this
        # specifies that the AutoBrand created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AutoBrand.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => auto_brand.to_param, :auto_brand => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested auto_brand as @auto_brand" do
        auto_brand = AutoBrand.create! valid_attributes
        put :update, {:id => auto_brand.to_param, :auto_brand => valid_attributes}, valid_session
        assigns(:auto_brand).should eq(auto_brand)
      end

      it "redirects to the auto_brand" do
        auto_brand = AutoBrand.create! valid_attributes
        put :update, {:id => auto_brand.to_param, :auto_brand => valid_attributes}, valid_session
        response.should redirect_to(auto_brand)
      end
    end

    describe "with invalid params" do
      it "assigns the auto_brand as @auto_brand" do
        auto_brand = AutoBrand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AutoBrand.any_instance.stub(:save).and_return(false)
        put :update, {:id => auto_brand.to_param, :auto_brand => { "name" => "invalid value" }}, valid_session
        assigns(:auto_brand).should eq(auto_brand)
      end

      it "re-renders the 'edit' template" do
        auto_brand = AutoBrand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AutoBrand.any_instance.stub(:save).and_return(false)
        put :update, {:id => auto_brand.to_param, :auto_brand => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested auto_brand" do
      auto_brand = AutoBrand.create! valid_attributes
      expect {
        delete :destroy, {:id => auto_brand.to_param}, valid_session
      }.to change(AutoBrand, :count).by(-1)
    end

    it "redirects to the auto_brands list" do
      auto_brand = AutoBrand.create! valid_attributes
      delete :destroy, {:id => auto_brand.to_param}, valid_session
      response.should redirect_to(auto_brands_url)
    end
  end

end
