require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DynamicPricesController do

  # This should return the minimal set of attributes required to create a valid
  # DynamicPrice. As you add validations to DynamicPrice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "price" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DynamicPricesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dynamic_prices as @dynamic_prices" do
      dynamic_price = DynamicPrice.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dynamic_prices).should eq([dynamic_price])
    end
  end

  describe "GET show" do
    it "assigns the requested dynamic_price as @dynamic_price" do
      dynamic_price = DynamicPrice.create! valid_attributes
      get :show, {:id => dynamic_price.to_param}, valid_session
      assigns(:dynamic_price).should eq(dynamic_price)
    end
  end

  describe "GET new" do
    it "assigns a new dynamic_price as @dynamic_price" do
      get :new, {}, valid_session
      assigns(:dynamic_price).should be_a_new(DynamicPrice)
    end
  end

  describe "GET edit" do
    it "assigns the requested dynamic_price as @dynamic_price" do
      dynamic_price = DynamicPrice.create! valid_attributes
      get :edit, {:id => dynamic_price.to_param}, valid_session
      assigns(:dynamic_price).should eq(dynamic_price)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DynamicPrice" do
        expect {
          post :create, {:dynamic_price => valid_attributes}, valid_session
        }.to change(DynamicPrice, :count).by(1)
      end

      it "assigns a newly created dynamic_price as @dynamic_price" do
        post :create, {:dynamic_price => valid_attributes}, valid_session
        assigns(:dynamic_price).should be_a(DynamicPrice)
        assigns(:dynamic_price).should be_persisted
      end

      it "redirects to the created dynamic_price" do
        post :create, {:dynamic_price => valid_attributes}, valid_session
        response.should redirect_to(DynamicPrice.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dynamic_price as @dynamic_price" do
        # Trigger the behavior that occurs when invalid params are submitted
        DynamicPrice.any_instance.stub(:save).and_return(false)
        post :create, {:dynamic_price => { "price" => "invalid value" }}, valid_session
        assigns(:dynamic_price).should be_a_new(DynamicPrice)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DynamicPrice.any_instance.stub(:save).and_return(false)
        post :create, {:dynamic_price => { "price" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dynamic_price" do
        dynamic_price = DynamicPrice.create! valid_attributes
        # Assuming there are no other dynamic_prices in the database, this
        # specifies that the DynamicPrice created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DynamicPrice.any_instance.should_receive(:update_attributes).with({ "price" => "" })
        put :update, {:id => dynamic_price.to_param, :dynamic_price => { "price" => "" }}, valid_session
      end

      it "assigns the requested dynamic_price as @dynamic_price" do
        dynamic_price = DynamicPrice.create! valid_attributes
        put :update, {:id => dynamic_price.to_param, :dynamic_price => valid_attributes}, valid_session
        assigns(:dynamic_price).should eq(dynamic_price)
      end

      it "redirects to the dynamic_price" do
        dynamic_price = DynamicPrice.create! valid_attributes
        put :update, {:id => dynamic_price.to_param, :dynamic_price => valid_attributes}, valid_session
        response.should redirect_to(dynamic_price)
      end
    end

    describe "with invalid params" do
      it "assigns the dynamic_price as @dynamic_price" do
        dynamic_price = DynamicPrice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DynamicPrice.any_instance.stub(:save).and_return(false)
        put :update, {:id => dynamic_price.to_param, :dynamic_price => { "price" => "invalid value" }}, valid_session
        assigns(:dynamic_price).should eq(dynamic_price)
      end

      it "re-renders the 'edit' template" do
        dynamic_price = DynamicPrice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DynamicPrice.any_instance.stub(:save).and_return(false)
        put :update, {:id => dynamic_price.to_param, :dynamic_price => { "price" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dynamic_price" do
      dynamic_price = DynamicPrice.create! valid_attributes
      expect {
        delete :destroy, {:id => dynamic_price.to_param}, valid_session
      }.to change(DynamicPrice, :count).by(-1)
    end

    it "redirects to the dynamic_prices list" do
      dynamic_price = DynamicPrice.create! valid_attributes
      delete :destroy, {:id => dynamic_price.to_param}, valid_session
      response.should redirect_to(dynamic_prices_url)
    end
  end

end
