require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MaintainsController do

  # This should return the minimal set of attributes required to create a valid
  # Maintain. As you add validations to Maintain, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "outlook_desc" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MaintainsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all maintains as @maintains" do
      maintain = Maintain.create! valid_attributes
      get :index, {}, valid_session
      assigns(:maintains).should eq([maintain])
    end
  end

  describe "GET show" do
    it "assigns the requested maintain as @maintain" do
      maintain = Maintain.create! valid_attributes
      get :show, {:id => maintain.to_param}, valid_session
      assigns(:maintain).should eq(maintain)
    end
  end

  describe "GET new" do
    it "assigns a new maintain as @maintain" do
      get :new, {}, valid_session
      assigns(:maintain).should be_a_new(Maintain)
    end
  end

  describe "GET edit" do
    it "assigns the requested maintain as @maintain" do
      maintain = Maintain.create! valid_attributes
      get :edit, {:id => maintain.to_param}, valid_session
      assigns(:maintain).should eq(maintain)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Maintain" do
        expect {
          post :create, {:maintain => valid_attributes}, valid_session
        }.to change(Maintain, :count).by(1)
      end

      it "assigns a newly created maintain as @maintain" do
        post :create, {:maintain => valid_attributes}, valid_session
        assigns(:maintain).should be_a(Maintain)
        assigns(:maintain).should be_persisted
      end

      it "redirects to the created maintain" do
        post :create, {:maintain => valid_attributes}, valid_session
        response.should redirect_to(Maintain.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved maintain as @maintain" do
        # Trigger the behavior that occurs when invalid params are submitted
        Maintain.any_instance.stub(:save).and_return(false)
        post :create, {:maintain => { "outlook_desc" => "invalid value" }}, valid_session
        assigns(:maintain).should be_a_new(Maintain)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Maintain.any_instance.stub(:save).and_return(false)
        post :create, {:maintain => { "outlook_desc" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested maintain" do
        maintain = Maintain.create! valid_attributes
        # Assuming there are no other maintains in the database, this
        # specifies that the Maintain created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Maintain.any_instance.should_receive(:update_attributes).with({ "outlook_desc" => "MyString" })
        put :update, {:id => maintain.to_param, :maintain => { "outlook_desc" => "MyString" }}, valid_session
      end

      it "assigns the requested maintain as @maintain" do
        maintain = Maintain.create! valid_attributes
        put :update, {:id => maintain.to_param, :maintain => valid_attributes}, valid_session
        assigns(:maintain).should eq(maintain)
      end

      it "redirects to the maintain" do
        maintain = Maintain.create! valid_attributes
        put :update, {:id => maintain.to_param, :maintain => valid_attributes}, valid_session
        response.should redirect_to(maintain)
      end
    end

    describe "with invalid params" do
      it "assigns the maintain as @maintain" do
        maintain = Maintain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Maintain.any_instance.stub(:save).and_return(false)
        put :update, {:id => maintain.to_param, :maintain => { "outlook_desc" => "invalid value" }}, valid_session
        assigns(:maintain).should eq(maintain)
      end

      it "re-renders the 'edit' template" do
        maintain = Maintain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Maintain.any_instance.stub(:save).and_return(false)
        put :update, {:id => maintain.to_param, :maintain => { "outlook_desc" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested maintain" do
      maintain = Maintain.create! valid_attributes
      expect {
        delete :destroy, {:id => maintain.to_param}, valid_session
      }.to change(Maintain, :count).by(-1)
    end

    it "redirects to the maintains list" do
      maintain = Maintain.create! valid_attributes
      delete :destroy, {:id => maintain.to_param}, valid_session
      response.should redirect_to(maintains_url)
    end
  end

end
