require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StorehousesController do

  # This should return the minimal set of attributes required to create a valid
  # Storehouse. As you add validations to Storehouse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StorehousesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all storehouses as @storehouses" do
      storehouse = Storehouse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:storehouses).should eq([storehouse])
    end
  end

  describe "GET show" do
    it "assigns the requested storehouse as @storehouse" do
      storehouse = Storehouse.create! valid_attributes
      get :show, {:id => storehouse.to_param}, valid_session
      assigns(:storehouse).should eq(storehouse)
    end
  end

  describe "GET new" do
    it "assigns a new storehouse as @storehouse" do
      get :new, {}, valid_session
      assigns(:storehouse).should be_a_new(Storehouse)
    end
  end

  describe "GET edit" do
    it "assigns the requested storehouse as @storehouse" do
      storehouse = Storehouse.create! valid_attributes
      get :edit, {:id => storehouse.to_param}, valid_session
      assigns(:storehouse).should eq(storehouse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Storehouse" do
        expect {
          post :create, {:storehouse => valid_attributes}, valid_session
        }.to change(Storehouse, :count).by(1)
      end

      it "assigns a newly created storehouse as @storehouse" do
        post :create, {:storehouse => valid_attributes}, valid_session
        assigns(:storehouse).should be_a(Storehouse)
        assigns(:storehouse).should be_persisted
      end

      it "redirects to the created storehouse" do
        post :create, {:storehouse => valid_attributes}, valid_session
        response.should redirect_to(Storehouse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved storehouse as @storehouse" do
        # Trigger the behavior that occurs when invalid params are submitted
        Storehouse.any_instance.stub(:save).and_return(false)
        post :create, {:storehouse => { "name" => "invalid value" }}, valid_session
        assigns(:storehouse).should be_a_new(Storehouse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Storehouse.any_instance.stub(:save).and_return(false)
        post :create, {:storehouse => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested storehouse" do
        storehouse = Storehouse.create! valid_attributes
        # Assuming there are no other storehouses in the database, this
        # specifies that the Storehouse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Storehouse.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => storehouse.to_param, :storehouse => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested storehouse as @storehouse" do
        storehouse = Storehouse.create! valid_attributes
        put :update, {:id => storehouse.to_param, :storehouse => valid_attributes}, valid_session
        assigns(:storehouse).should eq(storehouse)
      end

      it "redirects to the storehouse" do
        storehouse = Storehouse.create! valid_attributes
        put :update, {:id => storehouse.to_param, :storehouse => valid_attributes}, valid_session
        response.should redirect_to(storehouse)
      end
    end

    describe "with invalid params" do
      it "assigns the storehouse as @storehouse" do
        storehouse = Storehouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Storehouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => storehouse.to_param, :storehouse => { "name" => "invalid value" }}, valid_session
        assigns(:storehouse).should eq(storehouse)
      end

      it "re-renders the 'edit' template" do
        storehouse = Storehouse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Storehouse.any_instance.stub(:save).and_return(false)
        put :update, {:id => storehouse.to_param, :storehouse => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested storehouse" do
      storehouse = Storehouse.create! valid_attributes
      expect {
        delete :destroy, {:id => storehouse.to_param}, valid_session
      }.to change(Storehouse, :count).by(-1)
    end

    it "redirects to the storehouses list" do
      storehouse = Storehouse.create! valid_attributes
      delete :destroy, {:id => storehouse.to_param}, valid_session
      response.should redirect_to(storehouses_url)
    end
  end

end
